### ISSUE TITLE
software-based schedule implementation

### ISSUE THREAD

**Issue by plant310** [binfoo1993/TLPGNN#1]
Hi，I'm very interested in your work about the software-based assignment method，but it seems like the current implementations do not include this part，am I missing something or will this part be covered in a future update?

**Comment by charlifu** [comment]
Hi,

I appreciate your interest in my work!

The software-based workload assignment implementation for GCN and the test script are pushed.

Basically, it uses `atomicAdd` and the warp broadcast operation `__shfl_sync` to achieve the dynamic workload assignment method.

```C++
    if(threadIdx.x == 0) des_v = atomicAdd(n_done, 1);
    des_v = __shfl_sync(0xffffffff, des_v, 0, blockDim.x);
```

**Comment by plant310** [comment]
Thanks very much for your kind and in time help.
